### ISSUE TITLE
Backend Swift IP configuration is not allowed

### ISSUE THREAD

**Issue by bloodeagle40234** [swiftstack/ProxyFS#119]
swiftstack ProxyFS 1.5.3 can not be configurable that assign another Swift IP address than 127.0.0.1 because it's hard corded in the go swiftclient.

For performance consideration, it may be ok as design because setting other proxy server than localhost might cause performance issue from the connection over the IP network. However, the hard code to 127.0.0.1 is a bit problematic to my case because I'd like to configure my proxy-sever other than 0.0.0.0. (i.e. configure the swift's bind_ip to a specific out-bound network ip.) Then, proxyfsd can not talk with the proxy-server. 

I thought I may create a new proxy-server conf to bind to 127.0.0.1 but it will have resource overhead to make duplicate proxy-server caused by just a bind ib difference.

I tried to touch around the code to enable the backend swift ip as configurable [1], and it looks to work in my local environment. If it's suitable for ProxyFS community, I'll push a pull request to support the staff in upstream.

Any ideas?

1: https://github.com/bloodeagle40234/ProxyFS/commit/3fe824b735a7f0d12b470d07d694794dd9289e22

**Comment by edmc-ss** [comment]
Yes, the jrpcclient is currently assumed to be talking to the proxyfsd only on the same node. That said, the ipaddr being listened to by jrpcfs should actually be the cluster-facing ipaddr. This is because the pfs middleware in each Swift Proxy needs to be able to talk to any proxyfsd instance.

In any case, proxyfsd should not be listening on 0.0.0.0 as this would allow untrusted client machines to gain privileged access to the file system.

Longer term, there is a lot of interest in scaling out the jrpcclient function beyond just the local node where proxyfsd is running. Indeed, some folks are at work enabling the NFS protocol to leverage jrpcclient to gain this same scale out capability.

I'd love to hear others chime in on Kota's request as I think it an excellent one.

**Comment by edmc-ss** [comment]
I should add a bit more here.

The various .conf files in (primarily) the proxyfsd/ subdirectory are mere examples perhaps useful in development. As Kota points out, the proxyfsd process listens for connections on the PrivateIPAddr specified...and the examples in those .conf files are typically 127.0.0.1 - though this is easily changed.

I should also comment that one can try out config changes by overriding their values on the command line when starting proxyfsd by  following the .conf file with Section.Key=Value sequences. But in this case, Samba needs to know the PrivateIPAddr as well...so one minimally needs to (also) modify the smb.conf being used.

**Comment by bloodeagle40234** [comment]
Let me clarify my case. I meant the connectivity from proxyfsd to Swift cluster, the proxyfsd uses golang swiftclient that can connect only 127.0.0.1. I don't think the "proxyfsd -> swift" uses the jrpcclient but "swift pfs_middleware -> proxyfsd" does.

But anyway, configurable options for the cluster facing internal networ for BOTH "proxyfsd -> swift" and "swift -> proxyfsd" sounds nice to have to me.

**Comment by edmc-ss** [comment]
Aha Kota! Now I understand what you are looking at.

The proxyfsd process needs a path to Swift that does not have the pfs middleware in it. In addition, this path need not perform authorization since that has already been done. Indeed, at times it would be difficult bto associate requests for that the proxyfsd process makes to Swift with a particular client. In any event, the auth models of SMB & NFS are quite different than for Swift or S3.

As such, the ProxyFS setup requires what we call a "NoAuth" Swift Proxy pipeline. Lacking authorization, this pipeline certainly cannot bind to 0.0.0.0 lest unauthorized traffic do bad things. And, of course, such access would be presented with a rather incomprehensible set of checkpoint and file log segment objects. This would be akin to allowing normal processes access to the blocks on a disk formatted with a file system.


So you will see a NoAuth Swift Proxy instance (along side a normal Swift Proxy instance) on every ProxyFS node. This NoAuth Proxy binds specifically to localhost as you have observed and is only used by the colocated proxyfsd instance.

It sounds like you'd like it to be useable by other proxyfsd instances? Additionally, you'd like a given proxyfsd instance to be able to use NoAuth Proxies other than the one colocated with it.

I guess I don't understand why that would be beneficial.

One change that we could do is have the NoAuth Proxy binds to the cluster IP (the so-called PrivateIPAddr in the ProxyFS .conf files) and, then, proxyfsd could connect to that one (still colocated). Perhaps this is the change you are looking to do. A side benefit is that moving to an all IPv6 world would not require hard code changes of 127.0.0.1 to ::1 - not that moving to IPv6 necessarily eliminates the 127.0.0.X instance(s) of localhost...but it's a thought.

**Comment by bloodeagle40234** [comment]
> So you will see a NoAuth Swift Proxy instance (along side a normal Swift Proxy instance) on every ProxyFS node. This NoAuth Proxy binds specifically to localhost as you have observed and is only used by the colocated proxyfsd instance.

I think this is an constraint that any operators have to consider to compose proxyfsd and no-auth swift proxy any time then we cannot divide the operation between proxyfsd and swift proxy. An management issue is updating swift ring for the proxy, if we update the ring for capacity planning every proxyfsd node should be updated to get the new swift cluster object allocation. Then that might be painful.

> It sounds like you'd like it to be useable by other proxyfsd instances? Additionally, you'd like a given proxyfsd instance to be able to use NoAuth Proxies other than the one colocated with it.

Yes, saying more than operating issue above, actually we already operates no-auth proxy for our in-house fuse system that mounts swift cluster so at first, I'd like to re-use the no-auth swift endpoint but it's impossible in current proxyfsd deployments model.

> One change that we could do is have the NoAuth Proxy binds to the cluster IP (the so-called PrivateIPAddr in the ProxyFS .conf files) and, then, proxyfsd could connect to that one (still colocated). Perhaps this is the change you are looking to do.

I know. I already has the change[1] before this issue reported so if the proxyfsd community would think it as nice to have, I'll push a pull request for this. Before doing so, I'd hear the opinion if it's beneficial for proxyfsd community at the issue tracker following an OSS convention. 

1: https://github.com/bloodeagle40234/ProxyFS/commit/3fe824b735a7f0d12b470d07d694794dd9289e22

**Comment by edmc-ss** [comment]
So the real ask is to be able to separate proxyfsd from the no-auth-swift proxy. I see... interesting to understand why that would be helpful... this is not the swift proxy that clients use... it's only there to enable proxyfsd to talk to the cluster.

Meanwhile, did you suggest there is value in separating SMB/NFS serving (via jrpcclient) and proxyfsd? Much like how any proxy instance can talk to every proxyfsd instance in the cluster, the goal here would be able to allow any SMB (Samba->VFS->jrpclient) / NFS (Ganesha NFS->FSAL->jrpcclient) to talk to every proxyfsd instance in the cluster as well. What do you think about that?

**Comment by bloodeagle40234** [comment]
> Meanwhile, did you suggest there is value in separating SMB/NFS serving (via jrpcclient) and proxyfsd? Much like how any proxy instance can talk to every proxyfsd instance in the cluster, the goal here would be able to allow any SMB (Samba->VFS->jrpclient) / NFS (Ganesha NFS->FSAL->jrpcclient) to talk to every proxyfsd instance in the cluster as well. What do you think about that?

I'm not sure I get your mean correctly but it seems like, "yes". containerized processes for each endpoint (NFS, SMB, proxyfsd, and Swift Proxy) may be useful to make the cluster topology elastic. In fact, before trying to do this, I tried to build a docker container image to deploy proxyfsd (and NFS servers) to be located any cluster facing nodes, that is separated from Swift proxy. It was unfortunately not able though. That is because current proxyfs doesn't have any Ganesha NFS staffs so far.

If you don't like to get the elastic configuration, I don't want to continue to force to add the option here (probably, just forking in-house) but if you could think like 'it might be useful, it might be nice to have'. I'm happy with giving my pull request with a few fixes (like no-default configuration you suggested) in the future.

Thought?

**Comment by charmster** [comment]
hello @bloodeagle40234 
i've been asked to take a look at this issue. i would like to understand your motivation for making this change.  from what you've written, i understand the following:
* you are already running a *noauth proxy server* on one or more nodes in your cluster to support a FUSE driver for your Swift cluster and that noauth proxy server listens on an IP address that is not 127.0.0.1
* you prefer to avoid adding a second *noauth proxy server* that listens on 127.0.0.1 on that node because having two noauth proxy servers on the same node is a waste of some resources
* both the *"normal" Swift proxy server* and the *noauth proxy server* need to have the current Swift *ring configuration* to work properly; you are concerned that requiring the noauth proxy server run on the same node as a *proxyfs server* (proxyfsd) creates additional overhead for the administrator; this overhead could be avoided if the proxyfs server would talk to a noauth proxy server running on a node that is already maintained with the current configuration
* you also suggest that separating the *proxyfs server* from the *noauth proxy server* would make it easier to containerize the proxyfs server because the container would not need to include the current Swift ring configuration, just the IP address of a noauth proxy server it could use. with this change it would be easier to dynamically deploy additional proxyfs servers.

Is my understanding correct?

please note that, currently, a given bi-modal volume (proxyfs file system) can only be served by a single proxyfs server so different proxyfs servers will need to have different configuration files.  however the difference can be limited to the `WhoAmI` line in the proxyfs config file (but the other lines in the config files need to be consistent, or at least the lines describing the file system and which Peer serves which file system).

what are your thoughts?

**Comment by bloodeagle40234** [comment]
@charmster Thanks for clarifying my idea. Those look right. You understand my thought correctly. And the note is same with my understanding. So... my suggestion on this issue is we may have more flexible deployment model like separating proxyfs and swift-proxy nodes. The concern is just like as what you wrote down above.

**Comment by edmc-ss** [comment]
development now has @bloodeagle40234's PR addressing this issue...so closing now.

**Comment by bloodeagle40234** [comment]
much appreciated to get it merged!
