### ISSUE TITLE
Stringer may be missing in non swift-runway environment

### ISSUE THREAD

**Issue by bloodeagle40234** [swiftstack/ProxyFS#39]
When I was running, `python regression_test.py` according to README.md, that command failed with those lines as follows.

(NOTE: those lines are not all lines but some of failure lines)
blunder/api.go:58: running "stringer": exec: "stringer": executable file not found in $PATH
inode/validate_test.go:79:175: blunder.FsError(blunder.Errno(validationErr)).String undefined (type blunder.FsError has no field or method String)
FAIL	github.com/swiftstack/ProxyFS/inode [build failed]
`go install` succeeded!
`go generate` failed!
`go test` failed!
`go vet` succeeded!

It looks like we're missing to install stringer module. Then, after I installed string via `go get golang.org/x/tools/cmd/stringer` those failures were resolved and got succeeded.

**Comment by bloodeagle40234** [comment]
Ah... I found it looks like build_dependencies is trying to install the module. I'm not sure if it works well for now.

**Comment by bloodeagle40234** [comment]
Got it. Probably, this is from my fault at resolving path problem for go. No matter on ProxyFS script on this issue.

**Comment by edmc-ss** [comment]
Ah, yes, the issue is that your $GOPATH env must be defined (unless you use a very recent version of Go that defaults it) and $GOPATH/bin must be in your $PATH env.

The `runway` environment ensures both of these prerequisites are met... but if you are building outside of `runway`, you'll have to ensure these env's are set yourself.
